In [25]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv("./datasets/iris.csv")

In [27]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [28]:
from sklearn.datasets import load_iris

In [29]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [30]:
df.variety.value_counts()

variety
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

In [31]:
def Converter(cat):
    if cat == "Setosa":
        return 0
    if cat == "Versicolor":
        return 1
    if cat == "Virginica":
        return 2

In [32]:
print(Converter)

<function Converter at 0x0000024BAB491D00>

In [33]:
df["target"] = df.variety.apply(Converter)

In [34]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety  target
0             5.1          3.5           1.4          0.2     Setosa       0
1             4.9          3.0           1.4          0.2     Setosa       0
2             4.7          3.2           1.3          0.2     Setosa       0
3             4.6          3.1           1.5          0.2     Setosa       0
4             5.0          3.6           1.4          0.2     Setosa       0
..            ...          ...           ...          ...        ...     ...
145           6.7          3.0           5.2          2.3  Virginica       2
146           6.3          2.5           5.0          1.9  Virginica       2
147           6.5          3.0           5.2          2.0  Virginica       2
148           6.2          3.4           5.4          2.3  Virginica       2
149           5.9          3.0           5.1          1.8  Virginica       2

[150 rows x 6 columns]

In [35]:
sf_index = np.random.permutation(df.shape[0])

In [40]:
data  = df.iloc[sf_index].values
data

array([[4.4, 3.2, 1.3, 0.2, 'Setosa', 0],
       [5.7, 3.0, 4.2, 1.2, 'Versicolor', 1],
       [6.5, 3.2, 5.1, 2.0, 'Virginica', 2],
       [4.6, 3.2, 1.4, 0.2, 'Setosa', 0],
       [7.7, 3.8, 6.7, 2.2, 'Virginica', 2],
       [6.2, 3.4, 5.4, 2.3, 'Virginica', 2],
       [5.2, 3.5, 1.5, 0.2, 'Setosa', 0],
       [5.1, 3.8, 1.6, 0.2, 'Setosa', 0],
       [6.3, 2.8, 5.1, 1.5, 'Virginica', 2],
       [6.4, 3.1, 5.5, 1.8, 'Virginica', 2],
       [6.9, 3.1, 4.9, 1.5, 'Versicolor', 1],
       [5.2, 2.7, 3.9, 1.4, 'Versicolor', 1],
       [7.7, 3.0, 6.1, 2.3, 'Virginica', 2],
       [6.0, 2.9, 4.5, 1.5, 'Versicolor', 1],
       [4.7, 3.2, 1.3, 0.2, 'Setosa', 0],
       [6.0, 2.2, 5.0, 1.5, 'Virginica', 2],
       [6.1, 3.0, 4.9, 1.8, 'Virginica', 2],
       [4.5, 2.3, 1.3, 0.3, 'Setosa', 0],
       [5.1, 3.8, 1.9, 0.4, 'Setosa', 0],
       [4.9, 2.4, 3.3, 1.0, 'Versicolor', 1],
       [5.6, 2.7, 4.2, 1.3, 'Versicolor', 1],
       [5.8, 2.6, 4.0, 1.2, 'Versicolor', 1],
       [6.9, 3.2, 5.7, 2.3, 'Virginica', 2],
       [6.1, 2.6, 5.6, 1.4, 'Virginica', 2],
       [5.1, 3.5, 1.4, 0.2, 'Setosa', 0],
       [5.8, 4.0, 1.2, 0.2, 'Setosa', 0],
       [6.7, 3.0, 5.2, 2.3, 'Virginica', 2],
       [4.3, 3.0, 1.1, 0.1, 'Setosa', 0],
       [5.9, 3.0, 5.1, 1.8, 'Virginica', 2],
       [5.1, 3.8, 1.5, 0.3, 'Setosa', 0],
       [6.4, 2.8, 5.6, 2.2, 'Virginica', 2],
       [6.4, 3.2, 5.3, 2.3, 'Virginica', 2],
       [6.3, 2.3, 4.4, 1.3, 'Versicolor', 1],
       [6.0, 3.0, 4.8, 1.8, 'Virginica', 2],
       [6.3, 2.5, 4.9, 1.5, 'Versicolor', 1],
       [5.5, 2.4, 3.8, 1.1, 'Versicolor', 1],
       [6.4, 2.8, 5.6, 2.1, 'Virginica', 2],
       [4.9, 3.1, 1.5, 0.2, 'Setosa', 0],
       [5.5, 3.5, 1.3, 0.2, 'Setosa', 0],
       [5.0, 3.6, 1.4, 0.2, 'Setosa', 0],
       [6.7, 3.1, 4.4, 1.4, 'Versicolor', 1],
       [5.6, 2.5, 3.9, 1.1, 'Versicolor', 1],
       [6.2, 2.2, 4.5, 1.5, 'Versicolor', 1],
       [5.8, 2.7, 5.1, 1.9, 'Virginica', 2],
       [6.7, 3.0, 5.0, 1.7, 'Versicolor', 1],
       [6.7, 3.3, 5.7, 2.5, 'Virginica', 2],
       [5.7, 2.9, 4.2, 1.3, 'Versicolor', 1],
       [5.1, 3.7, 1.5, 0.4, 'Setosa', 0],
       [6.8, 3.0, 5.5, 2.1, 'Virginica', 2],
       [6.3, 3.4, 5.6, 2.4, 'Virginica', 2],
       [6.3, 2.7, 4.9, 1.8, 'Virginica', 2],
       [6.1, 3.0, 4.6, 1.4, 'Versicolor', 1],
       [4.7, 3.2, 1.6, 0.2, 'Setosa', 0],
       [4.8, 3.0, 1.4, 0.1, 'Setosa', 0],
       [6.7, 3.1, 4.7, 1.5, 'Versicolor', 1],
       [5.7, 4.4, 1.5, 0.4, 'Setosa', 0],
       [5.0, 3.5, 1.6, 0.6, 'Setosa', 0],
       [5.6, 3.0, 4.5, 1.5, 'Versicolor', 1],
       [4.9, 3.0, 1.4, 0.2, 'Setosa', 0],
       [6.7, 3.3, 5.7, 2.1, 'Virginica', 2],
       [5.8, 2.8, 5.1, 2.4, 'Virginica', 2],
       [7.7, 2.8, 6.7, 2.0, 'Virginica', 2],
       [7.1, 3.0, 5.9, 2.1, 'Virginica', 2],
       [5.5, 2.3, 4.0, 1.3, 'Versicolor', 1],
       [5.6, 2.9, 3.6, 1.3, 'Versicolor', 1],
       [5.2, 3.4, 1.4, 0.2, 'Setosa', 0],
       [6.5, 3.0, 5.8, 2.2, 'Virginica', 2],
       [4.4, 2.9, 1.4, 0.2, 'Setosa', 0],
       [4.4, 3.0, 1.3, 0.2, 'Setosa', 0],
       [6.9, 3.1, 5.4, 2.1, 'Virginica', 2],
       [5.7, 2.8, 4.5, 1.3, 'Versicolor', 1],
       [7.2, 3.6, 6.1, 2.5, 'Virginica', 2],
       [6.4, 2.7, 5.3, 1.9, 'Virginica', 2],
       [5.5, 4.2, 1.4, 0.2, 'Setosa', 0],
       [6.3, 3.3, 6.0, 2.5, 'Virginica', 2],
       [6.9, 3.1, 5.1, 2.3, 'Virginica', 2],
       [7.7, 2.6, 6.9, 2.3, 'Virginica', 2],
       [5.1, 2.5, 3.0, 1.1, 'Versicolor', 1],
       [5.1, 3.5, 1.4, 0.3, 'Setosa', 0],
       [7.6, 3.0, 6.6, 2.1, 'Virginica', 2],
       [5.0, 3.0, 1.6, 0.2, 'Setosa', 0],
       [5.5, 2.5, 4.0, 1.3, 'Versicolor', 1],
       [6.8, 3.2, 5.9, 2.3, 'Virginica', 2],
       [6.5, 3.0, 5.5, 1.8, 'Virginica', 2],
       [4.9, 2.5, 4.5, 1.7, 'Virginica', 2],
       [6.5, 2.8, 4.6, 1.5, 'Versicolor', 1],
       [6.0, 3.4, 4.5, 1.6, 'Versicolor', 1],
       [5.6, 3.0, 4.1, 1.3, 'Versicolor', 1],
       [6.1, 2.8, 4.7, 1.2, 'Versicolor', 1],
       [5.9, 3.2, 4.8, 1.8, 'Versicolor', 1],
       [5.7, 3.8, 1.7, 0.3, 'Setosa', 0],
       [4.6, 3.6, 1.0, 0.2, 'Setosa', 0],
       [6.7, 2.5, 5.8, 1.8, 'Virginica', 2],
       [6.2, 2.8, 4.8, 1.8, 'Virginica', 2],
       [5.4, 3.4, 1.7, 0.2, 'Setosa', 0],
       [5.0, 3.4, 1.5, 0.2, 'Setosa', 0],
       [4.9, 3.1, 1.5, 0.1, 'Setosa', 0],
       [6.7, 3.1, 5.6, 2.4, 'Virginica', 2],
       [6.3, 2.9, 5.6, 1.8, 'Virginica', 2],
       [6.1, 2.9, 4.7, 1.4, 'Versicolor', 1],
       [5.1, 3.3, 1.7, 0.5, 'Setosa', 0],
       [5.5, 2.6, 4.4, 1.2, 'Versicolor', 1],
       [4.8, 3.1, 1.6, 0.2, 'Setosa', 0],
       [5.6, 2.8, 4.9, 2.0, 'Virginica', 2],
       [4.6, 3.4, 1.4, 0.3, 'Setosa', 0],
       [5.5, 2.4, 3.7, 1.0, 'Versicolor', 1],
       [6.1, 2.8, 4.0, 1.3, 'Versicolor', 1],
       [5.4, 3.4, 1.5, 0.4, 'Setosa', 0],
       [4.8, 3.0, 1.4, 0.3, 'Setosa', 0],
       [6.0, 2.7, 5.1, 1.6, 'Versicolor', 1],
       [7.2, 3.2, 6.0, 1.8, 'Virginica', 2],
       [7.3, 2.9, 6.3, 1.8, 'Virginica', 2],
       [5.8, 2.7, 4.1, 1.0, 'Versicolor', 1],
       [5.7, 2.8, 4.1, 1.3, 'Versicolor', 1],
       [4.8, 3.4, 1.6, 0.2, 'Setosa', 0],
       [5.3, 3.7, 1.5, 0.2, 'Setosa', 0],
       [5.8, 2.7, 5.1, 1.9, 'Virginica', 2],
       [5.0, 2.3, 3.3, 1.0, 'Versicolor', 1],
       [6.4, 3.2, 4.5, 1.5, 'Versicolor', 1],
       [7.4, 2.8, 6.1, 1.9, 'Virginica', 2],
       [6.5, 3.0, 5.2, 2.0, 'Virginica', 2],
       [7.9, 3.8, 6.4, 2.0, 'Virginica', 2],
       [6.8, 2.8, 4.8, 1.4, 'Versicolor', 1],
       [5.0, 3.4, 1.6, 0.4, 'Setosa', 0],
       [6.6, 3.0, 4.4, 1.4, 'Versicolor', 1],
       [5.0, 3.5, 1.3, 0.3, 'Setosa', 0],
       [7.0, 3.2, 4.7, 1.4, 'Versicolor', 1],
       [5.4, 3.7, 1.5, 0.2, 'Setosa', 0],
       [5.0, 3.3, 1.4, 0.2, 'Setosa', 0],
       [6.4, 2.9, 4.3, 1.3, 'Versicolor', 1],
       [5.7, 2.6, 3.5, 1.0, 'Versicolor', 1],
       [5.7, 2.5, 5.0, 2.0, 'Virginica', 2],
       [4.9, 3.6, 1.4, 0.1, 'Setosa', 0],
       [6.3, 3.3, 4.7, 1.6, 'Versicolor', 1],
       [5.0, 2.0, 3.5, 1.0, 'Versicolor', 1],
       [5.1, 3.4, 1.5, 0.2, 'Setosa', 0],
       [4.6, 3.1, 1.5, 0.2, 'Setosa', 0],
       [4.8, 3.4, 1.9, 0.2, 'Setosa', 0],
       [7.2, 3.0, 5.8, 1.6, 'Virginica', 2],
       [5.0, 3.2, 1.2, 0.2, 'Setosa', 0],
       [5.9, 3.0, 4.2, 1.5, 'Versicolor', 1],
       [6.3, 2.5, 5.0, 1.9, 'Virginica', 2],
       [6.6, 2.9, 4.6, 1.3, 'Versicolor', 1],
       [5.4, 3.9, 1.3, 0.4, 'Setosa', 0],
       [5.4, 3.0, 4.5, 1.5, 'Versicolor', 1],
       [6.2, 2.9, 4.3, 1.3, 'Versicolor', 1],
       [5.8, 2.7, 3.9, 1.2, 'Versicolor', 1],
       [5.4, 3.9, 1.7, 0.4, 'Setosa', 0],
       [5.2, 4.1, 1.5, 0.1, 'Setosa', 0],
       [6.0, 2.2, 4.0, 1.0, 'Versicolor', 1]], dtype=object)

In [41]:
def Euclidean_Distance(Point1, Point2):
    if len(Point1) == len(Point2):
        return np.sqrt(np.sum((Point1[:4] - Point2[:4])**2))
    else:
        print("Shape should be same..")

In [42]:
Euclidean_Distance(data[0], data[0])

np.float64(0.0)

In [43]:
def Get_NN(TrainingData, testRow, K=3):
    Distance = []
    for oneRow in TrainingData:
        dis = Euclidean_Distance(oneRow, testRow)
        Distance.append(dis)
    

    Distance  = np.array(Distance)
    TrainingData = np.array(TrainingData)
    dis_index = Distance.argsort()
    TrainingData = TrainingData[dis_index]
    Nn = TrainingData[:K]
    Classes = []
    for n in Nn:
        Classes.append(n[-1])
    predClass = max(Classes, key= Classes.count)
    return predClass


Get_NN(data, data[10])



def Predict(testData):
    trainData = data
    out = []
    for test in testData:
        pred = Get_NN(trainData, test)
        out.append(pred)
    return np.array(out)


pred  = Predict(data)
pred

array([0, 1, 2, 0, 2, 2, 0, 0, 1, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 1,
       2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 1, 2, 2, 1, 2, 0, 0, 0, 1, 1, 1, 2,
       1, 2, 1, 0, 2, 2, 2, 1, 0, 0, 1, 0, 0, 1, 0, 2, 2, 2, 2, 1, 1, 0,
       2, 0, 0, 2, 1, 2, 2, 0, 2, 2, 2, 1, 0, 2, 0, 1, 2, 2, 1, 1, 1, 1,
       1, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 1, 0, 1, 0, 2, 0, 1, 1, 0, 0, 2,
       2, 2, 1, 1, 0, 0, 2, 1, 1, 2, 2, 2, 1, 0, 1, 0, 1, 0, 0, 1, 1, 2,
       0, 1, 1, 0, 0, 0, 2, 0, 1, 2, 1, 0, 1, 1, 1, 0, 0, 1])